<?php
/** @var \Endereco\Addressvalidation\Block\Customer\Address\ConfigData $block */

$configData = $block->jsonEncode($block->getConfig());

?>
<!-- Address validation configuration Endereco -->
<script type="text/javascript">
    if (!window.checkoutConfig) {
        window.checkoutConfig = <?= /* @noEscape */ $configData ?>;
        window.checkoutConfig.cccc.addressvalidation.endereco.email_check = false;
        window.checkoutConfig.cccc.addressvalidation.endereco.mapping.template = ".form-address-edit .field [name='##field##']";
    }
</script>
